name: Diff Files

on:
  pull_request:

jobs:
  diff_files:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dump GitHub Contexts
        run: |
          echo '${{ github.event_name }}'
          echo '${{ toJSON(github.event.pull_request ) }}'
        env:
          base_ref: ${{ github.event.pull_request.base.ref }}
          head_ref: ${{ github.event.pull_request.head.ref }}
          changed_files: ${{ github.event.pull_request.changed_files }}

      - name: Diff Files > pull_request.base.sha - pull_request.head.sha
        run: |
          git diff --name-only $BASE_SHA...$HEAD_SHA
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          commits: ${{ github.event.pull_request.commits }}

      - name: Diff Files > origin/base_ref - sha
        run: |
          BASE_SHA=$(git rev-parse origin/${{ github.base_ref }})
          echo $BASE_SHA
          git diff --name-only $BASE_SHA...${{ github.sha }}

      - name: Diff Files > sha back to commits - sha
        run: |
          git diff --name-only ${{ github.sha }}~${{ github.event.pull_request.commits }}...${{ github.sha }}
