name: Diff Files

on:
  pull_request:

jobs:
  diff_files:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Dump GitHub Contexts
        run: |
          echo '${{ github.event_name }}'
          echo '${{ toJSON(github.event.pull_request ) }}'
        env:
          base_ref: ${{ github.event.pull_request.base.ref }}
          head_ref: ${{ github.event.pull_request.head.ref }}
          changed_files: ${{ github.event.pull_request.changed_files }}
