name: Diff Files

on:
  pull_request:

jobs:
  diff_files:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dump GitHub Contexts
        run: |
          echo '${{ github.event_name }}'
          echo '${{ toJSON(github.event.pull_request ) }}'
        env:
          base_ref: ${{ github.event.pull_request.base.ref }}
          head_ref: ${{ github.event.pull_request.head.ref }}
          changed_files: ${{ github.event.pull_request.changed_files }}

      - name: Diff Files
        run: |
          git diff --name-only $BASE_SHA...$HEAD_SHA
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}

      - name: Diff Files 2
        run: |
          BASE_SHA=$(git rev-parse origin/${{ github.base_ref }})
          git diff --name-only $BASE_SHA...${{ github.sha }}
