name: Diff Files

on:
  pull_request:

jobs:
  diff_files:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Diff Files In Pull Request
        uses: ./.github/actions/get-diff-files-in-pr
        with:
          output-file: './diff_files.txt'

      - name: Show Diff Files
        run: cat ./diff_files.txt
