name: Diff Files

on:
  pull_request:

jobs:
  diff_files:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/diff-files-in-pr
        id: get-diff-files

      - name: Dump GitHub Contexts
        run: |
          echo '${{ github.event_name }}'
          echo '${{ toJSON(github.event.pull_request ) }}'
        env:
          base_ref: ${{ github.event.pull_request.base.ref }}
          head_ref: ${{ github.event.pull_request.head.ref }}
          changed_files: ${{ github.event.pull_request.changed_files }}

      - name: Git Log
        run: git log --oneline

      - name: Diff Files > pull_request.base.sha - pull_request.head.sha
        run: |
          git diff --name-only $BASE_SHA...$HEAD_SHA
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          commits: ${{ github.event.pull_request.commits }}

      - name: Diff Files > origin/base_ref - sha
        run: |
          BASE_SHA=$(git rev-parse origin/${{ github.base_ref }})
          echo BASE_SHA: $BASE_SHA
          git diff --name-only $BASE_SHA...${{ github.sha }}

      - name: Diff Files > sha back to commits - sha
        run: |
          echo HEAD_SHA: $(git rev-parse HEAD)
          # マージ前のコミットを取得
          BEFORE_MERGE_SHA=$(git rev-parse HEAD^2)
          echo BEFORE_MERGE_SHA: $BEFORE_MERGE_SHA
          BASE_SHA=$(git rev-parse $BEFORE_MERGE_SHA~${{ github.event.pull_request.commits }})
          echo BASE_SHA: $BASE_SHA
          git diff --name-only $BASE_SHA...${{ github.sha }}
